export enum ClinicalSigns {
  VOMIT = "Vômito",
  FEVER = "Febre",
  ATAXY = "Ataxia",
  DYSPNEA = "Dispneia",
  ANOREXIA = "Anorexia",
  DIARRHEA = "Diarreia",
  MYOCLONUS = "Mioclonia",
  DRY_COUGH = "Tosse seca",
  SIALORRHEA = "Sialorreia",
  EYE_DISCHARGE = "Secreção ocular",
  CONJUNCTIVITIS = "Conjuntivite",
  NASAL_DISCHARGE = "Secreção nasal",
  ABDOMINAL_PUSTULES = "Pústulas abdominais",
  NASAL_HYPERKERATOSIS = "Hiperqueratose Nasal",
}
